title = 'Synthetic Yeast: Sc2.0'
baseURL = 'https://syntheticyeast.github.io/'
languageCode = 'en-us'
theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 7
googleAnalytics = ""
enableRobotsTXT = true
buildDrafts = true

[params]
  author = ""
  favicon = ""
  site_logo = ""
  description = "Building the world's first synthetic eukaryotic genome together"
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/final_copy-2.png"
  recent_posts_number = 4

  [markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
